version: "3"

services:
    postgres:
        container_name: db-restaurante-34
        hostname: db-restaurante-34
        image: postgres:latest
        ports:
            - "5432:5432"
        expose:
            - 5432
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - default

    api:
        container_name: restaurante-34-api
        hostname: restaurante-34-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        expose:
            - 3001
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            DB_NAME: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - default
        restart: always
        depends_on:
            - postgres

networks:
    default:
        driver: bridge

volumes:
    pg_data:
