version: '3.8'

services:
  db:
    container_name: db-restaurante-34
    hostname: db-restaurante-34
    image: postgres:latest    
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    container_name: app-restaurante-34
    hostname: app-restaurante-34
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    expose:
      - 3001
    environment:
      - DATABASE_URL=postgresql://root:root@db/postgres
      - PRISMA_CLIENT_LOG=['query', 'info', 'warn']
    volumes:
      - app_data:/usr/src/app/dist
    depends_on:
      - db
    restart: always
    command: ["npm", "start"]

volumes:
  app_data: