apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
spec:
  ports:
  - nodePort: 31001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: restaurante34apiaeployment
  type: NodePort