apiVersion: apps/v1
kind: Deployment
metadata:
    name: restaurante34apiaeployment
    labels:
        app: restaurante34apiaeployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: restaurante34apiaeployment
    template:
        metadata:
            labels:
                app: restaurante34apiaeployment
        spec:
            containers:
                - name: restaurante34apiaeployment
                  env:
                      - name: POSTGRES_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: db-configmap
                                key: POSTGRES_HOST
                      - name: POSTGRES_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: db-configmap
                                key: POSTGRES_PORT
                      - name: DB_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: db-configmap
                                key: DB_NAME
                      - name: COGNITO_JWKS_URL
                        value: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_2iqIrXWTh/.well-known/jwks.json"
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-credentials
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-credentials
                                key: POSTGRES_PASSWORD
                  image: 450872441741.dkr.ecr.us-east-1.amazonaws.com/restaurant-34:3
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3001
                  resources:
                      requests:
                          cpu: "50m"
                          memory: "100Mi"
                      limits:
                          cpu: "2500m"
                          memory: "256Mi"
                  livenessProbe:
                      httpGet:
                          path: /api/health/
                          port: 3001
                      initialDelaySeconds: 30
                      periodSeconds: 10
