apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: cm9vdA==
  DATABASE_URL: cG9zdGdyZXNxbDovL3l1cmk6ZlgyVmR3OURlQHJlc3RhdXJhbnQtMzQuY2p3aXdzdzZxZHNnLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVzP3NjaGVtYT1wdWJsaWM=